package com.company.speedment.orm.test.polaroid.db0.polaroid.follow.impl;

import com.company.speedment.orm.test.polaroid.db0.polaroid.follow.Follow;
import com.company.speedment.orm.test.polaroid.db0.polaroid.follow.FollowBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.follow'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class FollowImpl implements FollowBuilder {
    
    private Long follower;
    private String follows;
    
    public FollowImpl() {
        
    }
    
    public FollowImpl(final Follow follow) {
        setFollower(follow.getFollower());
        setFollows(follow.getFollows());
    }
    
    @Override
    public Long getFollower() {
        return follower;
    }
    
    @Override
    public FollowImpl setFollower(Long follower) {
        this.follower = follower;
        return this;
    }
    
    @Override
    public String getFollows() {
        return follows;
    }
    
    @Override
    public FollowImpl setFollows(String follows) {
        this.follows = follows;
        return this;
    }
    
    @Override
    public Follow build() {
        return new FollowImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("follower = "+Objects.toString(getFollower()));
        sj.add("follows = "+Objects.toString(getFollows()));
        return "FollowImpl "+sj.toString();
    }
}