package com.company.speedment.orm.test.polaroid.db0.polaroid.image.impl;

import com.company.speedment.orm.test.polaroid.db0.polaroid.image.Image;
import com.company.speedment.orm.test.polaroid.db0.polaroid.image.ImageBuilder;
import java.sql.Timestamp;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.image'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class ImageImpl implements ImageBuilder {
    
    private Long id;
    private Long uploader;
    private String title;
    private String description;
    private String imgData;
    private Timestamp uploaded;
    
    public ImageImpl() {
        
    }
    
    public ImageImpl(final Image image) {
        setId(image.getId());
        setUploader(image.getUploader());
        setTitle(image.getTitle());
        setDescription(image.getDescription());
        setImgData(image.getImgData());
        setUploaded(image.getUploaded());
    }
    
    @Override
    public Long getId() {
        return id;
    }
    
    @Override
    public ImageImpl setId(Long id) {
        this.id = id;
        return this;
    }
    
    @Override
    public Long getUploader() {
        return uploader;
    }
    
    @Override
    public ImageImpl setUploader(Long uploader) {
        this.uploader = uploader;
        return this;
    }
    
    @Override
    public String getTitle() {
        return title;
    }
    
    @Override
    public ImageImpl setTitle(String title) {
        this.title = title;
        return this;
    }
    
    @Override
    public String getDescription() {
        return description;
    }
    
    @Override
    public ImageImpl setDescription(String description) {
        this.description = description;
        return this;
    }
    
    @Override
    public String getImgData() {
        return imgData;
    }
    
    @Override
    public ImageImpl setImgData(String imgData) {
        this.imgData = imgData;
        return this;
    }
    
    @Override
    public Timestamp getUploaded() {
        return uploaded;
    }
    
    @Override
    public ImageImpl setUploaded(Timestamp uploaded) {
        this.uploaded = uploaded;
        return this;
    }
    
    @Override
    public Image build() {
        return new ImageImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("uploader = "+Objects.toString(getUploader()));
        sj.add("title = "+Objects.toString(getTitle()));
        sj.add("description = "+Objects.toString(getDescription()));
        sj.add("imgData = "+Objects.toString(getImgData()));
        sj.add("uploaded = "+Objects.toString(getUploaded()));
        return "ImageImpl "+sj.toString();
    }
}