package com.company.speedment.orm.test.polaroid.db0.polaroid.user.impl;

import com.company.speedment.orm.test.polaroid.db0.polaroid.user.User;
import com.company.speedment.orm.test.polaroid.db0.polaroid.user.UserBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class UserImpl implements UserBuilder {
    
    private Long id;
    private String mail;
    private String password;
    private String firstName;
    private String lastName;
    private String avatar;
    
    public UserImpl() {
        
    }
    
    public UserImpl(final User user) {
        setId(user.getId());
        setMail(user.getMail());
        setPassword(user.getPassword());
        setFirstName(user.getFirstName());
        setLastName(user.getLastName());
        setAvatar(user.getAvatar());
    }
    
    @Override
    public Long getId() {
        return id;
    }
    
    @Override
    public UserImpl setId(Long id) {
        this.id = id;
        return this;
    }
    
    @Override
    public String getMail() {
        return mail;
    }
    
    @Override
    public UserImpl setMail(String mail) {
        this.mail = mail;
        return this;
    }
    
    @Override
    public String getPassword() {
        return password;
    }
    
    @Override
    public UserImpl setPassword(String password) {
        this.password = password;
        return this;
    }
    
    @Override
    public String getFirstName() {
        return firstName;
    }
    
    @Override
    public UserImpl setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }
    
    @Override
    public String getLastName() {
        return lastName;
    }
    
    @Override
    public UserImpl setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }
    
    @Override
    public String getAvatar() {
        return avatar;
    }
    
    @Override
    public UserImpl setAvatar(String avatar) {
        this.avatar = avatar;
        return this;
    }
    
    @Override
    public User build() {
        return new UserImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("mail = "+Objects.toString(getMail()));
        sj.add("password = "+Objects.toString(getPassword()));
        sj.add("firstName = "+Objects.toString(getFirstName()));
        sj.add("lastName = "+Objects.toString(getLastName()));
        sj.add("avatar = "+Objects.toString(getAvatar()));
        return "UserImpl "+sj.toString();
    }
}