package com.company.speedment.orm.test.polaroid.db0.polaroid.user;

import com.speedment.orm.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface UserBuilder extends User, Buildable<User> {
    
    UserBuilder setId(Long id);
    
    UserBuilder setMail(String mail);
    
    UserBuilder setPassword(String password);
    
    UserBuilder setFirstName(String firstName);
    
    UserBuilder setLastName(String lastName);
    
    UserBuilder setAvatar(String avatar);
}