package com.company.speedment.orm.test.polaroid.db0.polaroid.follow;

import com.speedment.orm.config.model.Column;
import com.speedment.orm.config.model.Table;
import com.speedment.orm.core.manager.SqlManager;
import com.speedment.orm.platform.Platform;
import com.speedment.orm.platform.component.ManagerComponent;
import com.speedment.orm.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.follow'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface FollowManager extends SqlManager<List<?>, Follow, FollowBuilder> {
    
    @Override
    default List<?> primaryKeyFor(Follow entity) {
        return Arrays.asList(entity.getFollower(), entity.getFollows());
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("db0.polaroid.follow");
    }
    
    @Override
    default Class<FollowManager> getManagerClass() {
        return FollowManager.class;
    }
    
    @Override
    default Class<Follow> getEntityClass() {
        return Follow.class;
    }
    
    @Override
    default Class<FollowBuilder> getBuilderClass() {
        return FollowBuilder.class;
    }
    
    @Override
    default Object get(Follow entity, Column column) {
        switch (column.getName()) {
            case "follower" : return entity.getFollower();
            case "follows" : return entity.getFollows();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static FollowManager get() {
        return (FollowManager) Platform.get().get(ManagerComponent.class).manager(FollowManager.class);
    }
}