package com.company.speedment.orm.test.polaroid.db0.polaroid.link;

import com.speedment.orm.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.link'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface LinkBuilder extends Link, Buildable<Link> {
    
    LinkBuilder setFollower(Long follower);
    
    LinkBuilder setFollows(Long follows);
}