package com.company.speedment.orm.test.polaroid.db0.polaroid.link;

import com.company.speedment.orm.test.polaroid.db0.polaroid.user.User;
import com.company.speedment.orm.test.polaroid.db0.polaroid.user.UserManager;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.link'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface Link {
    
    Long getFollower();
    
    Long getFollows();
    
    default User findFollower() {
        return UserManager.get()
                .stream().filter(user -> Objects.equals(this.getFollower(), user.getId())).findAny().get();
    }
    
    default User findFollows() {
        return UserManager.get()
                .stream().filter(user -> Objects.equals(this.getFollows(), user.getId())).findAny().get();
    }
    
    static LinkBuilder builder() {
        return LinkManager.get().builder();
    }
    
    default LinkBuilder toBuilder() {
        return LinkManager.get().toBuilder(this);
    }
    
    static Stream<Link> stream() {
        return LinkManager.get().stream();
    }
    
    default Optional<Link> persist() {
        return LinkManager.get().persist(this);
    }
    
    default Optional<Link> update() {
        return LinkManager.get().update(this);
    }
    
    default Optional<Link> remove() {
        return LinkManager.get().remove(this);
    }
}