package com.company.speedment.orm.test.polaroid;

import com.speedment.orm.runtime.SpeedmentApplicationLifecycle;

/**
 * A Speedment Application Lifecycle representing an entity (for example, a row) in the Project 'polaroid'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class PolaroidApplication extends SpeedmentApplicationLifecycle<PolaroidApplication> {
    
    public PolaroidApplication() {
        setConfigDirectoryName("src/main/groovy");
        setConfigFileName("speedment.groovy");
    }
    
    @Override
    public void onInit() {
        loadAndSetProject();
        put(new com.company.speedment.orm.test.polaroid.db0.polaroid.user.impl.UserManagerImpl());
        put(new com.company.speedment.orm.test.polaroid.db0.polaroid.image.impl.ImageManagerImpl());
        put(new com.company.speedment.orm.test.polaroid.db0.polaroid.link.impl.LinkManagerImpl());
        super.onInit();
    }
}