package com.company.speedment.orm.test.polaroid.db0.polaroid.image;

import com.speedment.orm.core.Buildable;
import java.sql.Timestamp;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.image'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface ImageBuilder extends Image, Buildable<Image> {
    
    ImageBuilder setId(Long id);
    
    ImageBuilder setUploader(Long uploader);
    
    ImageBuilder setTitle(String title);
    
    ImageBuilder setDescription(String description);
    
    ImageBuilder setImgData(String imgData);
    
    ImageBuilder setUploaded(Timestamp uploaded);
}