package com.company.speedment.orm.test.polaroid.db0.polaroid.link.impl;

import com.company.speedment.orm.test.polaroid.db0.polaroid.link.Link;
import com.company.speedment.orm.test.polaroid.db0.polaroid.link.LinkBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'polaroid.db0.polaroid.link'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class LinkImpl implements LinkBuilder {
    
    private Long follower;
    private Long follows;
    
    public LinkImpl() {
        
    }
    
    public LinkImpl(final Link link) {
        setFollower(link.getFollower());
        setFollows(link.getFollows());
    }
    
    @Override
    public Long getFollower() {
        return follower;
    }
    
    @Override
    public LinkImpl setFollower(Long follower) {
        this.follower = follower;
        return this;
    }
    
    @Override
    public Long getFollows() {
        return follows;
    }
    
    @Override
    public LinkImpl setFollows(Long follows) {
        this.follows = follows;
        return this;
    }
    
    @Override
    public Link build() {
        return new LinkImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("follower = "+Objects.toString(getFollower()));
        sj.add("follows = "+Objects.toString(getFollows()));
        return "LinkImpl "+sj.toString();
    }
}